name: grin_mates
description: A Flutter-based eco-friendly mobile dApp on Celo blockchain
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  web3dart: ^2.7.1
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  intl: ^0.18.1
  logger: ^2.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.4
  animate_do: ^3.1.2
  url_launcher: ^6.3.0
  image_picker: ^1.0.4
  walletconnect_flutter_v2: ^2.3.1
  web3modal_flutter: ^3.0.0
  web3auth_flutter: ^6.1.2
  flutter_launcher_icons: ^0.14.3

  vibration: ^3.1.4
  image: ^4.1.0
  google_fonts: ^6.3.2
  smooth_page_indicator: ^1.2.1
  # animate_do: ^3.1.2
  # get_it: ^7.6.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/metamask_logo.png
    - assets/images/logo.png
    - assets/images/onboarding.png
    - assets/images/eco.png
    - assets/images/lock.png

